name: Test And Lint

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Run Lint
        run: pnpm lint
      - name: Run Test
        run: pnpm test
      - name: Run Test coverage
        run: pnpm test:cov

